<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">

<!-- VOLVO_GPSS_ARHO and FORKLIFT -->
<xacro:property name="robot_type" value="FORKLIFT"/>


    <xacro:property name="base_length" value="1.4"/>
    <xacro:property name="base_width" value="0.86"/> <!-- wheel_separation -->
    <xacro:property name="base_height" value="0.315"/>
    <xacro:property name="base_mass" value="155"/>  <!-- base_mass + wheel_mass = 175 -->
    <xacro:property name="wheel_mass" value="5"/>
    <xacro:property name="wheel_separation" value="0.86"/> <!-- base_width -->
    <xacro:property name="wheel_width" value="0.02"/>
    <xacro:property name="wheel_radius" value="0.1"/>

    <xacro:property name="scan_px" value="0.0"/>
    <xacro:property name="scan_py" value="0.0"/>
    <xacro:property name="scan_pz" value="${base_height+2.5}"/>

    <xacro:property name="camera_px" value="${base_length/2}"/>
    <xacro:property name="camera_py" value="0.0"/>
    <xacro:property name="camera_pz" value="${base_height+1.6}"/>

    <xacro:property name="infobot_friction" value="0.1"/>
    <xacro:property name="infobot_slip" value="0.0"/>
    <xacro:property name="infobot_damping" value="0.7"/>

    <xacro:property name="infobot_slide_range" value="2"/>

<!--GOPAL 400 :  https://www.mobile-robots.de/files/554/factsheet-mr-robotize-gopal-400-e24-09-22-en-min.pdf -->
<xacro:if value="${robot_type == 'GOPAL400'}">

    <xacro:property name="fork_size_x" value="1.2"/>
    <xacro:property name="fork_size_y" value="0.1"/>
    <xacro:property name="fork_size_z" value="0.1"/>



    <xacro:property name="fork_pos_x" value="0.0"/>
    <xacro:property name="fork_separation" value="0.2"/>
    <xacro:property name="fork_pos_z" value="0.0"/>

</xacro:if>

<!-- FORKLIFT -->
<xacro:if value="${robot_type == 'FORKLIFT'}">

    <xacro:property name="fork_size_x" value="1.2"/>
    <xacro:property name="fork_size_y" value="0.1"/>
    <xacro:property name="fork_size_z" value="0.1"/>


    <xacro:property name="fork_pos_x" value="1.3"/>
    <xacro:property name="fork_separation" value="0.2"/>
    <xacro:property name="fork_pos_z" value="-0.3"/>

</xacro:if>





</robot>
