import os

PALLET_TRUCK_NAVIGATION_PKG_PATH = os.path.expanduser("~/src/simulation/pallet_truck/pallet_truck_navigation")

def generate_bt_xml(robots):

    xml_template = """<root BTCPP_format="4" main_tree_to_execute="MainTree">
        <BehaviorTree ID="MainTree">

            <!-- Main sequence -->
            <PipelineSequence name="MainSequence">

            <!-- Failsafe: stops robot if out of bounds -->
            <Fallback name="StopIfOutOfBounds">
                <StopRobotCondition robot_ns="{namespace}"/>
                <CancelControl/>
            </Fallback>

            <!-- Normal navigation -->
            <PipelineSequence name="NavigateWithReplanning">

                <!-- Compute path (throttled to 1 Hz) -->
                <RateController hz="1.0">
                <ComputePathToPose goal="{{goal}}" path="{{path}}" planner_id="GridBased"/>
                </RateController>

                <!-- Follow path -->
                <FollowPath path="{{path}}" controller_id="FollowPath"/>

            </PipelineSequence>

            </PipelineSequence>

        </BehaviorTree>
    </root>
    """

    header_comment = """<!--
##########################################################################################################################
# This file was auto-generated by: /home/ros/src/simulation/pallet_truck/pallet_truck_bringup/launch/generate_bt_xml.py  #
##########################################################################################################################
-->"""

    for robot in robots:
        namespace = robot["namespace"]
        file=f"navigate_w_replanning_and_recovery_{namespace}.xml"
        output_path = os.path.join(
            PALLET_TRUCK_NAVIGATION_PKG_PATH,
            "config",
            file
        )

        os.makedirs(os.path.dirname(output_path), exist_ok=True)

        with open(output_path, "w") as f:
            f.write(header_comment + "\n\n")
            f.write(xml_template.format(namespace=namespace))

        print(f"Generated config: {file}")
