/**:
  twist_mux:
    ros__parameters:
      use_stamped: false
      topics:
        navigation:
          topic   : nav_vel
          timeout : 0.5
          priority: 10
        keyboard:
          topic   : key_vel
          timeout : 0.5
          priority: 100
        safety:
          topic   : safety_vel
          timeout : 0.5
          priority: 80  
        scenario:
          topic   : scenario_vel
          timeout : 0.5
          priority: 50