humanoid:
  # This config file is used by ros2_control
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      support_whole_body_controller:
        type: joint_trajectory_controller/JointTrajectoryController
      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
      velocity_controller:
        type: diff_drive_controller/DiffDriveController

  support_whole_body_controller:
    ros__parameters:
      joints:
        - link1_link2_joint
        - link2_link3_joint
        - link3_link4_joint
        - jL5S1_rotx
        - jL5S1_roty
        - jT9T8_rotx
        - jT9T8_roty
        - jT9T8_rotz
        - jC7LeftShoulder_rotx
        - jLeftShoulder_rotx
        - jLeftShoulder_roty
        - jLeftShoulder_rotz
        - jLeftElbow_roty
        - jLeftElbow_rotz
        - jLeftWrist_rotx
        - jLeftWrist_rotz
        - jC7RightShoulder_rotx
        - jRightShoulder_rotx
        - jRightShoulder_roty
        - jRightShoulder_rotz
        - jRightElbow_roty
        - jRightElbow_rotz
        - jRightWrist_rotx
        - jRightWrist_rotz
        - jT1C7_rotx
        - jT1C7_roty
        - jT1C7_rotz
        - jC1Head_rotx
        - jC1Head_roty
        - jLeftHip_rotx
        - jLeftHip_roty
        - jLeftHip_rotz
        - jLeftKnee_roty
        - jLeftKnee_rotz
        - jLeftAnkle_rotx
        - jLeftAnkle_roty
        - jLeftAnkle_rotz
        - jLeftBallFoot_roty
        - jRightHip_rotx
        - jRightHip_roty
        - jRightHip_rotz
        - jRightKnee_roty
        - jRightKnee_rotz
        - jRightAnkle_rotx
        - jRightAnkle_roty
        - jRightAnkle_rotz
        - jRightBallFoot_roty
      command_interfaces:
        - position
      state_interfaces:
        - position
        - velocity

#### WHEELS 

  velocity_controller:
    ros__parameters:
      left_wheel_names: ["humanoid_front_left_wheel_joint", "humanoid_rear_left_wheel_joint"]
      right_wheel_names: ["humanoid_front_right_wheel_joint", "humanoid_rear_right_wheel_joint"]
      wheel_separation: 0.36
      wheels_per_side: 1
      wheel_radius: 0.098
      wheel_separation_multiplier: 1.5
      left_wheel_radius_multiplier: 1.0
      right_wheel_radius_multiplier: 1.0

      publish_rate: 50.0
      odom_frame_id: odom
      base_frame_id: arm_base_link
      pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
      twist_covariance_diagonal: [1000000.0, 1000000.0, 0.03, 1000000.0, 1000000.0, 0.03]
      open_loop: false
      enable_odom_tf: false
      cmd_vel_timeout: 0.25
      preserve_turning_radius: true
      publish_cmd: true
      publish_wheel_data: true

      linear.x.has_velocity_limits: true
      linear.x.has_acceleration_limits: true
      linear.x.max_velocity: 2.0
      linear.x.min_velocity: -2.0
      linear.x.max_acceleration: 20.0
      linear.x.min_acceleration: -20.0
      linear.x.max_jerk: NaN
      linear.x.min_jerk: NaN

      angular.z.has_velocity_limits: true
      angular.z.has_acceleration_limits: true
      angular.z.max_velocity: 4.0
      angular.z.min_velocity: -4.0
      angular.z.max_acceleration: 25.0
      angular.z.min_acceleration: -25.0
      angular.z.max_jerk: NaN
      angular.z.min_jerk: NaN
